<#
.SYNOPSIS
    Builds the FollowMeFree Service MSI installer.

.DESCRIPTION
    1. Publishes the WorkerService project (framework-dependent, no PDBs).
    2. Auto-generates SupportFiles.wxs listing every published file except the main EXE.
    3. Builds the WiX installer project to produce the MSI.

.PARAMETER Configuration
    Build configuration (Debug or Release). Default: Release.

.EXAMPLE
    .\build-installer.ps1
    .\build-installer.ps1 -Configuration Debug
#>
param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Release"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$root        = $PSScriptRoot
$workerProj  = Join-Path $root "FollowMeFree.WorkerService\FollowMeFree.WorkerService.csproj"
$publishDir  = Join-Path $root "FollowMeFree.WorkerService\bin\publish"
$installerDir = Join-Path $root "FollowMeFree.Installer"
$installerProj = Join-Path $installerDir "FollowMeFree.Installer.wixproj"
$supportWxs  = Join-Path $installerDir "SupportFiles.wxs"
$exeName     = "FollowMeFree.WorkerService.exe"

# ── Step 1: Publish ──────────────────────────────────────────────────────────
Write-Host "`n== Publishing FollowMeFree.WorkerService ==" -ForegroundColor Cyan
dotnet publish $workerProj -c $Configuration -o $publishDir -p:DebugType=none -p:DebugSymbols=false
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed (exit code $LASTEXITCODE)." }
Write-Host "Published to: $publishDir" -ForegroundColor Green

# ── Step 2: Generate SupportFiles.wxs ────────────────────────────────────────
Write-Host "`n== Generating SupportFiles.wxs ==" -ForegroundColor Cyan

$publishDirFull = (Resolve-Path $publishDir).Path.TrimEnd('\')

# Collect every file except the service EXE and PDBs
$files = Get-ChildItem -Path $publishDirFull -File -Recurse | Where-Object {
    $_.Name -ne $exeName -and $_.Extension -ne ".pdb"
}

# ── Helper: deterministic short ID from a relative path ──
function Get-SafeId {
    param([string]$RelativePath)
    $id = $RelativePath -replace '[^a-zA-Z0-9_]', '_'
    if ($id.Length -le 60) { return $id }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = [System.BitConverter]::ToString(
        $sha.ComputeHash(
            [System.Text.Encoding]::UTF8.GetBytes($RelativePath)
        )
    ).Replace("-", "").Substring(0, 8)
    $sha.Dispose()
    return $id.Substring(0, 51) + "_" + $hash
}

# ── Helper: directory-ID for a relative subdirectory ──
function Get-DirId {
    param([string]$RelativeDir)
    if ([string]::IsNullOrEmpty($RelativeDir)) { return "INSTALLFOLDER" }
    return "dir_" + ($RelativeDir -replace '[^a-zA-Z0-9_]', '_')
}

# ── Build a nested tree of subdirectories ──
$dirTree = [ordered]@{}
$uniqueDirs = $files | ForEach-Object {
    $rel = $_.FullName.Substring($publishDirFull.Length + 1)
    [System.IO.Path]::GetDirectoryName($rel)
} | Where-Object { $_ } | Sort-Object -Unique

foreach ($dir in $uniqueDirs) {
    $parts   = $dir -split '\\'
    $current = $dirTree
    for ($i = 0; $i -lt $parts.Length; $i++) {
        $part = $parts[$i]
        if (-not $current.Contains($part)) {
            $current[$part] = [ordered]@{
                _id       = Get-DirId ($parts[0..$i] -join '\')
                _children = [ordered]@{}
            }
        }
        $current = $current[$part]._children
    }
}

# ── Recursive XML writer for <Directory> elements ──
function Write-DirXml {
    param($Tree, [int]$Indent)
    $xml = ""
    $pad = " " * $Indent
    foreach ($key in $Tree.Keys) {
        $node = $Tree[$key]
        if ($node._children.Count -gt 0) {
            $xml += "${pad}<Directory Id=`"$($node._id)`" Name=`"$key`">`n"
            $xml += (Write-DirXml $node._children ($Indent + 2))
            $xml += "${pad}</Directory>`n"
        } else {
            $xml += "${pad}<Directory Id=`"$($node._id)`" Name=`"$key`" />`n"
        }
    }
    return $xml
}

# ── Assemble the WXS ──
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sb.AppendLine('<!-- Auto-generated by build-installer.ps1 – do not edit manually. -->')
[void]$sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
[void]$sb.AppendLine('  <Fragment>')

# Directory tree (only if there are subdirectories)
if ($dirTree.Count -gt 0) {
    [void]$sb.AppendLine('    <DirectoryRef Id="INSTALLFOLDER">')
    [void]$sb.Append((Write-DirXml $dirTree 6))
    [void]$sb.AppendLine('    </DirectoryRef>')
}

# Component group
[void]$sb.AppendLine('    <ComponentGroup Id="SupportFiles">')
foreach ($file in $files) {
    $relPath = $file.FullName.Substring($publishDirFull.Length + 1)
    $relDir  = [System.IO.Path]::GetDirectoryName($relPath)
    $safeId  = Get-SafeId $relPath
    $dirId   = Get-DirId  $relDir

    [void]$sb.AppendLine("      <Component Id=`"cmp_$safeId`" Directory=`"$dirId`" Guid=`"*`">")
    [void]$sb.AppendLine("        <File Id=`"file_$safeId`" Source=`"`$(var.PublishDir)\$relPath`" KeyPath=`"yes`" />")
    [void]$sb.AppendLine("      </Component>")
}
[void]$sb.AppendLine('    </ComponentGroup>')

[void]$sb.AppendLine('  </Fragment>')
[void]$sb.AppendLine('</Wix>')

$sb.ToString() | Out-File -FilePath $supportWxs -Encoding UTF8
Write-Host "Generated: $supportWxs ($($files.Count) support files)" -ForegroundColor Green

# ── Step 3: Build the MSI ────────────────────────────────────────────────────
Write-Host "`n== Building MSI Installer ==" -ForegroundColor Cyan
dotnet build $installerProj -c $Configuration "-p:ServicePublishDir=$publishDir"
if ($LASTEXITCODE -ne 0) { throw "WiX build failed (exit code $LASTEXITCODE)." }

$msiDir = Join-Path $installerDir "bin\x64\$Configuration"
$msi = Get-ChildItem -Path $msiDir -Filter "*.msi" -ErrorAction SilentlyContinue | Select-Object -First 1

if ($msi) {
    Write-Host "`nInstaller built successfully!" -ForegroundColor Green
    Write-Host "  MSI: $($msi.FullName)" -ForegroundColor White
} else {
    Write-Host "`nBuild completed. Check output in: $msiDir" -ForegroundColor Yellow
}
