//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FollowMeFree
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintJob
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string DocumentName { get; set; }
        public int JobId { get; set; }
        public int Pages { get; set; }
        public System.DateTime DateTimePrinted { get; set; }
        public string DataType { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PrinterId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Printer Printer { get; set; }
    }
}
